# Generated by Django 2.0.5 on 2020-01-20 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('taste', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('date', models.DateField()),
            ],
        ),
    ]
